title: Klaudija Kaurin # your name (or website title) here
logo: "/images/7ecfc6f1-cfb9-408b-9fb2-a78362edf6e2.jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
  Date of birth: 03.04.2002.
  <br>
  Age: 19
  <br>
  Location: Novska, Croatia
  <br>
  E-mail: klaudijakaurin18@gmail.com
  <br>
 
  
 
  Programming skills: C#, HTML
  <br>
  
  Database: Firebase
   <br>
   
   3D modeling and animations: Sweet home 3D, Make human, Fuse, Mixamo
  <br>
  
  Digital art: Canva
   <br>
   
  Other software: Github
<br>
  
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

